In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataKelulusan.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [4]:
dataset

Nama  Umur    Gaji KeteranganTetap
0   Ikhwan Fila  21.0  4000.0             Yes
1  Fara Darniva  21.0  3500.0             Yes
2  Irgi Saputra  21.0  4000.0             Yes
3   Ikhwan Fila  25.0  5500.0             Yes
4  Fara Darniva  25.0     NaN             Yes
5  Irgi Saputra  25.0  5500.0             NaN
6   Ikhwan Fila   NaN  6500.0             Yes
7  Fara Darniva  30.0  6000.0              No
8  Irgi Saputra  30.0  6300.0             Yes
9        Ikhwan  32.0  7600.0              No

In [5]:
print(X)

[['Ikhwan Fila' 21.0 4000.0]
 ['Fara Darniva' 21.0 3500.0]
 ['Irgi Saputra' 21.0 4000.0]
 ['Ikhwan Fila' 25.0 5500.0]
 ['Fara Darniva' 25.0 nan]
 ['Irgi Saputra' 25.0 5500.0]
 ['Ikhwan Fila' nan 6500.0]
 ['Fara Darniva' 30.0 6000.0]
 ['Irgi Saputra' 30.0 6300.0]
 ['Ikhwan' 32.0 7600.0]]


In [6]:
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'Yes' nan 'Yes' 'No' 'Yes' 'No']


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [8]:
print(X)

[['Ikhwan Fila' 21.0 4000.0]
 ['Fara Darniva' 21.0 3500.0]
 ['Irgi Saputra' 21.0 4000.0]
 ['Ikhwan Fila' 25.0 5500.0]
 ['Fara Darniva' 25.0 5433.333333333333]
 ['Irgi Saputra' 25.0 5500.0]
 ['Ikhwan Fila' 25.555555555555557 6500.0]
 ['Fara Darniva' 30.0 6000.0]
 ['Irgi Saputra' 30.0 6300.0]
 ['Ikhwan' 32.0 7600.0]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[0.0 0.0 1.0 0.0 21.0 4000.0]
 [1.0 0.0 0.0 0.0 21.0 3500.0]
 [0.0 0.0 0.0 1.0 21.0 4000.0]
 [0.0 0.0 1.0 0.0 25.0 5500.0]
 [1.0 0.0 0.0 0.0 25.0 5433.333333333333]
 [0.0 0.0 0.0 1.0 25.0 5500.0]
 [0.0 0.0 1.0 0.0 25.555555555555557 6500.0]
 [1.0 0.0 0.0 0.0 30.0 6000.0]
 [0.0 0.0 0.0 1.0 30.0 6300.0]
 [0.0 1.0 0.0 0.0 32.0 7600.0]]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[1 1 1 1 1 2 1 0 1 0]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)

In [14]:
print(X_train)

[[0.0 0.0 1.0 0.0 25.555555555555557 6500.0]
 [1.0 0.0 0.0 0.0 25.0 5433.333333333333]
 [0.0 0.0 1.0 0.0 21.0 4000.0]
 [0.0 0.0 1.0 0.0 25.0 5500.0]
 [1.0 0.0 0.0 0.0 21.0 3500.0]
 [1.0 0.0 0.0 0.0 30.0 6000.0]
 [0.0 0.0 0.0 1.0 30.0 6300.0]
 [0.0 0.0 0.0 1.0 25.0 5500.0]]


In [15]:
print(X_test)

[[0.0 0.0 0.0 1.0 21.0 4000.0]
 [0.0 1.0 0.0 0.0 32.0 7600.0]]


In [16]:
print(y_train)

[1 1 1 1 1 0 1 2]


In [17]:
print(y_test)

[1 0]


In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [19]:
print(X_train)

[[0.0 0.0 1.0 -0.5773502691896258 0.07397810009236287 1.1624170385728378]
 [1.0 0.0 0.0 -0.5773502691896258 -0.10008801777201852
  0.09198983758490109]
 [0.0 0.0 1.0 -0.5773502691896258 -1.3533640663955608 -1.3463967137426383]
 [0.0 0.0 1.0 -0.5773502691896258 -0.10008801777201852
  0.15889153764664743]
 [1.0 0.0 0.0 -0.5773502691896258 -1.3533640663955608 -1.8481594642057335]
 [1.0 0.0 0.0 -0.5773502691896258 1.4665070430074094 0.6606542881097427]
 [0.0 0.0 0.0 1.7320508075688774 1.4665070430074094 0.9617119383875998]
 [0.0 0.0 0.0 1.7320508075688774 -0.10008801777201852 0.15889153764664743]]


In [20]:
print(X_test)

[[0.0 0.0 0.0 1.7320508075688774 -1.3533640663955608 -1.3463967137426383]
 [0.0 1.0 0.0 -0.5773502691896258 2.0931450673191807 2.2662950895916474]]
